version: '3.7'

services:

  sample-db:
    image: mysql:8.3
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sampledb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

  file-service:
    build: .
    ports:
      - "9090:8080"
    environment:
      spring_profiles_active: default
    links:
      - sample-db
