logging:
  level:
    root: WARN
    org.springframework: INFO
    uk.co.mulecode.fileservice: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: file-service-poc
    description: v1

server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /app

spring:
  messages:
    basename: lang/messages

  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 1MB

  liquibase:
    contexts: dev
    defaultSchema: sampledb
    enabled: true
    liquibaseSchema: sampledb

  datasource:
    url: jdbc:mysql://sample-db:3306/sampledb?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: sampledb
        ddl-auto: validate
        dialect: org.hibernate.dialect.MySQLDialect

application:
  name: file-service-poc
  features-flags:
    enable-csv-file-validation: true
  features-configs:
    ip-verification-partner-url: http://ip-api.com/json/
