@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor User
box "acme"
    participant API
    participant Service
end box

User -> API: Submit CSV file
activate API

alt "is request valid"
    API -> Service: Process CSV file
    activate Service
    Service --> API: Processed Json file
    deactivate Service
    API --> User: Return JSON response
else
API -[#red]->  User: Return Bad Request
end alt

deactivate API
@enduml
