name: Pull Request

on:
  pull_request:
    types: [ opened, edited, synchronize, labeled, unlabeled ]

permissions:
  id-token: write
  contents: read

jobs:

  java_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Java Test
        run: make test
