name: Pull Request

on:
  pull_request:
    types: [ opened, edited, synchronize, labeled, unlabeled ]

permissions:
  id-token: write
  contents: read

jobs:

  java_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - package: "component/**"
          - package: "config/**"
          - package: "controller/**"
          - package: "listener/**"
          - package: "repository/**"
          - package: "service/**"
          - package: "RunCucumberTest.java"
    steps:
      - uses: actions/checkout@v4
      - name: ${{ matrix.package }} Test
        run: make test PACKAGE="${{ matrix.package }}"
